
## File autogenerated by genmodel.py

from sqlalchemy import *
meta = MetaData()


radios = Table('radios', meta,
    Column('id', Integer, primary_key=True, nullable=False),
    Column('user_id', Integer, nullable=False),
    Column('name', Text, nullable=False),
    Column('website', Text),
    Column('description', Text),
    Column('genre', Text),
    Column('last_seen', DateTime),
    Column('longitude', Float),
    Column('latitude', Float),
    Column('artist', Text),
    Column('title', Text, nullable=False),
)

streams = Table('streams', meta,
    Column('radio_id', Integer),
    Column('format', Text, nullable=False),
    Column('url', Text, nullable=False),
    Column('msg', Text),
)

users = Table('users', meta,
    Column('id', Integer, primary_key=True, nullable=False),
    Column('user', Text, nullable=False),
    Column('password', Text, nullable=False),
    Column('email', Text),
    Column('alive', Text),
    Column('last_seen', DateTime),
    Column('last_ip', Text),
)

